version: '3.5'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    image: ask
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=password

volumes:
  redis:
  postgres:
